#!/bin/sh

# if asdf java is not installed, install and configure it
if ! asdf which nodejs &>/dev/null; then
    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    asdf install nodejs lts
    asdf set -u nodejs lts
    echo "asdf java nodejs lts has been installed and set globally via asdf."
else    
    echo "asdf java is already installed."
fi