#!/bin/sh

# if asdf java is not installed, install and configure it
if ! asdf which java &>/dev/null; then
    asdf asdf plugin add java https://github.com/halcyon/asdf-java.git
    asdf install java openjdk-23
    asdf set -u java openjdk-23
    echo "asdf java adoptopenjdk-23 has been installed and set globally via asdf."
else    
    echo "asdf java is already installed."
fi